#!/bin/bash
set -e
cd "$(dirname "$0")/.."
HOMEBREW_PREFIX=$(brew --config | grep HOMEBREW_PREFIX | sed 's/HOMEBREW_PREFIX: //')

brew list redis > /dev/null 2>&1 || (
  brew install redis
  brew services restart redis
)

brew list mysql > /dev/null 2>&1 || (
  brew install mysql
  brew services start mysql
)

brew list postgresql > /dev/null 2>&1 || brew install postgresql

brew list memcached > /dev/null 2>&1 || brew install memcached

rbenv which ruby >/dev/null 2>&1 || (brew upgrade ruby-build || true; rbenv install)

# Setup rbenv so we can switch rubies below
eval "$(rbenv init - --no-rehash)"

if [ ! -e Gemfile ]; then
  tput bold    # bold text
  tput setaf 2 # red text
  echo "Gemfile symlink is broken. Should point to a known good Gemfile-x variant in ./gemfiles"
  tput sgr0    # reset to default text
  exit 199
elif [ ! -e Gemfile.lock ]; then
  tput bold    # bold text
  tput setaf 2 # red text
  echo "Gemfile.lock symlink is broken. Should point to a known good Gemfile-x.lock variant in ./gemfiles"
  tput sgr0    # reset to default text
  exit 200
fi

for ruby_version in `ruby -ryaml -e 'puts YAML.load(File.read(".travis.yml"))["rvm"].join(" ")'`; do
  rbenv versions --bare | grep "^${ruby_version}$" || rbenv install $ruby_version
  rbenv shell $ruby_version

  # WARNING: If you change the versions here, make sure to change .travis.yml
  gem list -i bundler --version 2.0.2 >/dev/null || gem install bundler --version 2.0.2
  # Remove this when the gem lock files are all updated to use Bundler 2.0
  # See https://stackoverflow.com/questions/54087856/cant-find-gem-bundler-0-a-with-executable-bundle-gemgemnotfoundexceptio/54088849#54088849
  gem list -i bundler --version 1.17.3 >/dev/null || gem install bundler --version 1.17.3
  
  gem list -i gemika >/dev/null || gem install gemika

  rake -t matrix:install
done

if ! psql postgres -tc "SELECT 1 FROM pg_database WHERE datname = 'metrician_test'" | grep -q 1; then
  psql -c 'create database metrician_test;' postgres
fi
mysql -e 'create database IF NOT EXISTS metrician_test;' -u root

if [ ! -f spec/support/database.yml ]; then
  tput bold    # bold text
  tput setaf 2 # red text
  echo "spec/support/database.yml doesn't exist, run:"
  echo "  cp spec/support/database.sample.yml spec/support/database.yml"
  echo
  echo "and update the credentials to match your system"
  tput sgr0    # reset to default text
else
  tput bold    # bold text
  tput setaf 2 # green text
  echo "****************************************************************"
  echo "*                                                              *"
  echo "*                         Good to go!                          *"
  echo "*                                                              *"
  echo "****************************************************************"
  tput sgr0    # reset to default text
fi

