#!/bin/bash
set -e
cd "$(dirname "$0")/.."

eval "$(rbenv init - --no-rehash)"

success="true"

for ruby_version in `ruby -ryaml -e 'puts YAML.load(File.read(".travis.yml"))["rvm"].join(" ")'`; do
  {
    echo "testing rub version $ruby_version" &&
      rbenv shell $ruby_version &&
      bundle exec rake matrix:spec
  } || success="false"
done

if [ $success == "true" ]; then
  tput bold    # bold text
  tput setaf 2 # green text
  echo "======================================"
  echo "               Passed"
  echo "======================================"
  tput sgr0    # reset to default text
else
  tput bold    # bold text
  tput setaf 2 # red text
  echo "======================================"
  echo "               FAILED"
  echo "======================================"
  tput sgr0    # reset to default text
fi
