#!/bin/bash
set -e
cd "$(dirname "$0")/.."

eval "$(rbenv init - --no-rehash)"

success="true"

for ruby_version in `ruby -ryaml -e 'puts YAML.load(File.read(".travis.yml"))["rvm"].join(" ")'`; do
  {
    echo "testing rub version $ruby_version" &&
      rbenv shell $ruby_version &&
      bundle exec rake matrix:spec
  } || success="false"
done

     TEST_RED='\033[1;31m'
   TEST_GREEN='\033[1;32m'
TEST_NO_COLOR='\033[0;0m'
if [ $success == "true" ]; then
  echo -e "${TEST_GREEN}"
  echo -e "======================================"
  echo -e "               Passed"
  echo -e "======================================"
  echo -e "${TEST_NO_COLOR}"
else
  echo -e "${TEST_RED}"
  echo -e "======================================"
  echo -e "               FAILED"
  echo -e "======================================"
  echo -e "${TEST_NO_COLOR}"
fi
